baseURL = "https://dream-plus-posts.netlify.com"
title = "Innovation Activators"
theme = "dream"
#themesDir = "../.."		#Don't use this, only for exampleSite
paginate = 4
enableRobotsTXT = true
disqusShortname = "dream-plus"

#Skip building these files
ignoreFiles = ["content/404.md", "content/about.md", "content/cards/\\.*"]

#Syntax highlighting
pygmentsCodeFences = false
pygmentsUseClasses = false
pygmentsOptions = "linenos=table"

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	#Favicon for site
	favicon = "/img/defaultFav.ico"

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	siteStartYear = 2018

	[params.author]
		name = "Innovation Activators"
		description = "Enter IA's description here."
		avatar = "/ia.png"
		motto = "Add IA's motto."

	[params.features]
		#Enable Twitter Emoji
		twitterEmoji = false
		#Enable Table of Contents
		toc = false
		#Enable share card
		shareCard = false
		#Use custom CSS
		customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]

	#Tags settings
	[params.tags]
		enabled = false

	#Categories settings
	[params.categories]
		enabled = false

[social]
	email = "utkarshverma@pm.me"
	github = "UtkarshVerma"
	stackoverflow = "9271608/utkarsh-verma"
	medium = "UtkarshVerma_"
	twitter = "UtkarshVerma_"
